### PR TITLE
Hopefully fixes #4

### LINKED ISSUE #4: Problem with zoltan
Traceback (most recent call last):
  File "/pysph/setup.py", line 482, in <module>
    setup_package()
  File "/pysph/setup.py", line 404, in setup_package
    create_sources()
  File "/pysph/setup.py", line 393, in create_sources
    print(check_output(cmd).decode())
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'pyzoltan/core/generator.py', '/pyzoltan/core']' returned non-zero exit status 2

### PR DESCRIPTION
**Pull request by adityapb**
CMD runs during runtime. Thus zoltan isn't installed when image is built.

### CODE REVIEW

**Comment by adityapb** [comment]
Merge only after testing

**Comment by adityapb** [comment]
Added build_zoltan.sh.Try again

**Comment by adityapb** [comment]
Permission issue should be fixed. Try again

**Comment by adityapb** [comment]
Python wasn't installed. Try again.

**Comment by Anmol1696** [comment]
Python was installed
its just that there is a file named python in /usr/bin not a dir

**Comment by adityapb** [comment]
Problem was solved!

**Pull request closed without merging**
